print('{:=^50}'.format('MÉDIA DE DUAS NOTAS'))
n1=float(input('Digite a 1º nota: '))
n2=float(input('Digite a 2º nota: '))
print('A sua média é igual a {:.1f}.'.format((n1+n2)/2))
print('{:=^50}'.format('='))