v=input('Digite alguma coisa: ')
print('O tipo primitivo é', type(v))
print('É numérico? ',(v.isnumeric()))
print('É alpha-numérico? ',(v.isalnum()))
print('É alfabético? ',(v.isalpha()))
print('É todo maiúsculo? ',(v.isupper()))
print('É numérico? ',(v.isnumeric()))
print('É decimal? ',(v.isdecimal()))
print('É todo minúsculo? ',(v.islower()))
print('É imprimível? ',(v.isprintable()))
