print('{:=^50}'.format('OPERAÇÕES'))
n=float(input('Número 1: '))
n2=float(input('Número 2: '))
p=float(n ** n2)
s=float(n+n2)
menos=float(n-n2)
m=float(n*n2)
d=float(n/n2)
di=float(n//n2)
r=float(n%n2)
print('{} - {} é igual a {}'.format(n,n2,menos))
print('{} vezes {} é igual a {}'.format(n,n2,m))
print('{} + {} é igual a {}'.format(n,n2,s))
print('{} dividido por {} é igual a {:3f}'.format(n,n2,d))
print('A divisão inteira de {} por {} é igual a {}'.format(n,n2,di))
print('{} elevado a {} é igual a {}' .format(n,n2,p))
print('O módulo de {} dividido por {} é igual a {}'.format(n,n2,r))
print('{:=^50}'.format('='))